### ISSUE TITLE
Minor aesthetic issue: reorder submenu item

### ISSUE THREAD

**Issue by dsboger** [kgshank/gse-disconnect-wifi#11]
Hi! Thanks for this extension!

I would like to suggest, in the name of consistency, that you would put the "Disconnect/Reconnect" menu item above the "Settings" item (which is always the last in every submenu). It would feel more "integrated" to me.

Like I said, minor issue!

**Comment by kgshank** [comment]
Updated extension in extensions website, wait for approval and verify
