### ISSUE TITLE
Please tag a release for v19

### ISSUE THREAD

**Issue by highvoltage** [kgshank/gse-disconnect-wifi#16]
Hi! It seems like V19 has been released, but not been tagged, can you please tag it so that distributions that follow the project can know that they have to update it? thanks for your work!

**Comment by kgshank** [comment]
Hi Johnathan,

Created a new release with new version, but used a different tag for identification. Updated now. Latest release https://github.com/kgshank/gse-disconnect-wifi/releases/tag/19.0.3.30
