### ISSUE TITLE
Extension "disconnect-wifi@kgshank.net" had error: TypeError: this._gsettings is undefined

### ISSUE THREAD

**Issue by gnarendran** [kgshank/gse-disconnect-wifi#17]
Error after recent update to version 19 of "Disconnect WiFi", with gnome-shell-3.28.3-1, Fedora 28.

Workaround: In spite of the error, if one changes the setting "Always show Reconnect option" a dconf key is created and the error is solved.

Regards

**Comment by kgshank** [comment]
Released a new update, it should fix the issue
