### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by liubomirwm** [kgshank/gse-disconnect-wifi#20]
The settings of extension disconnect-wifi@kgshank.net had an error:
```
ReferenceError: global is not defined
```

Stack trace:
```
log@/home/lyubomir/.local/share/gnome-shell/extensions/disconnect-wifi@kgshank.net/convenience.js:138:9
_init@/home/lyubomir/.local/share/gnome-shell/extensions/disconnect-wifi@kgshank.net/prefs.js:64:17
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
buildPrefsWidget@/home/lyubomir/.local/share/gnome-shell/extensions/disconnect-wifi@kgshank.net/prefs.js:83:27
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by liubomirwm** [comment]
The extension updated and settings now open, but there is a red "ERROR" and i don't see the disconnect option.

**Comment by kgshank** [comment]
Sometimes, the update from extensions.gnome.org

If the error occurs after a shell restart / logout-login. Try uninstalling completely and reinstalling the extension

**Comment by liubomirwm** [comment]
Hmm, that's not good. I logged out and back in, still "ERROR" and not working.
Then i uninstaled it, logged out and logged in again, after which i reinstalled it. Immediately after installing it showed red "ERROR". I once again logged out and then logged in. It was still not working. I then restarted Gnome shell and the red "ERROR" disappeared, but it's still not showing the "Disconnect" option.
Settings open correctly, but no matter whether Reconnect option is on or off, still not showing the disconnect option. Neither reconnect.

**Comment by marcinzelent** [comment]
Can confirm, error when trying to install.

**Comment by marcinzelent** [comment]
Where can I find them?

**Comment by liubomirwm** [comment]
[journalctl-gnome-extensions.log](https://github.com/kgshank/gse-disconnect-wifi/files/4678400/journalctl-gnome-extensions.log)
@kgshank Is this what you're asking for? I can't find anything related to disconnect-wifi.

**Comment by liubomirwm** [comment]
https://drive.google.com/file/d/1XkhoIA--83YBJ748lcpiN4pfAnjBG3CW/view?usp=sharing
That's a link to log, perhaps that's what you're looking for @kgshank?

**Comment by cutiyar** [comment]
After the update the extension could not be added and gives red error, i have tried removing it and adding again, logout and login, didn't help.
now its not working.

**Comment by Scotty-Trees** [comment]
I'm experiencing the red error message as well, making the extension not show up in the menu, regardless of reinstalling log out/in, etc. Good luck, hope you find a fix!

**Comment by kgshank** [comment]
There was an  error with the earlier update. I have taken it down. A fixed version is uploaded, it should be available soon after approval. My apologies for inconvenience
