### ISSUE TITLE
_l is not a function

### ISSUE THREAD

**Issue by frague59** [kgshank/gse-disconnect-wifi#22]
Hi, 

```sh
$ gnome-shell --version 
GNOME Shell 3.36.2
```
With version 22 I've an error on extension initialization (when I install it)
`TypeError: _l is not a function`

I can see this error in looking glass (Alt+F2 lg)

I've tried to uninstall / reinstall it, always the same error...

Thanks for this extension !

**Comment by kgshank** [comment]
V24 fixes the issue, but its not approved in extensions.gnome.org yet. You can get the latest git version and replace the files directly.

**Comment by frague59** [comment]
I've installed it, ti works - Thanks !
