### ISSUE TITLE
Feature: reconnect at any time

### ISSUE THREAD

**Issue by adamhassel** [kgshank/gse-disconnect-wifi#26]
I'd find it immensely useful to have a reconnect button available at all times, so I can disconnect and reconnect my current network at any time with a single click. My issue is that when I dock/undock my laptop, I sometimes lose the connection, even though the OS thinks it's still there, so I need to reconnect to reestablish.

At the current stage, this extension is semantically equivalent to clicking "Turn Off" followed by "Turn On" to reconnect to the last connected network.

**Comment by kgshank** [comment]
The option is already available in the extension settings. Let me know whether you are looking for a different behaviour

**Comment by adamhassel** [comment]
So it is! Thank you. I didn't even see there were settings :D Thanks a bunch!

**Comment by adamhassel** [comment]
Actually, for me that only disconnects. I need to click the "Reconnect" button a second time for the connection to be reestablished...

**Comment by kgshank** [comment]
@adamhassel The fixes are released in Git, i didnt notice that the option didnt work as expected. My apologies
