### ISSUE TITLE
Reconnect option only disconnects, does not connect again

### ISSUE THREAD

**Issue by anupam207** [kgshank/gse-disconnect-wifi#29]
**Steps to reproduce:**

1. Turn on '**Always show Reconnect option**' in the extension preferences.
2. Observe there's a "_Reconnect SSID_" option in the Wi-Fi system menu when it is already connected to SSID. Click it.

**Expected behaviour:**
Wi-Fi disconnects and then reconnects to the same SSID.

**What happens:**
Wi-Fi only disconnects. Need to click the Reconnect option again to connect to the same SSID.

**System info:**
OS: Ubuntu 20.04.1 LTS
GNOME Shell version: 3.36.3
Extension version: 26 (installed from extensions.gnome.org)

**Comment by kgshank** [comment]
Git has fixes, will take time to be approved in extensions.gnome.org

**Comment by anupam207** [comment]
Looks like it got fixed with the recent update (extensions.gnome.org version).
