### ISSUE TITLE
Once in a while the extension fails and cannot be restarted

### ISSUE THREAD

**Issue by frol** [kgshank/gse-disconnect-wifi#3]
Once it fails, the "ON/OFF" switch is greyed out in Tweak Tool and extensions.gnome.org has red "ERROR" button instead of the switch, so I have to remove the extension via Tweak Tool and install it back via extensions.gnome.org. I have faced this issue about 4-5 times in the last 3 months.

**Comment by RaphaelRochet** [comment]
The issue is easy to reproduce : restart your shell a few times (via Alt+f2 then R). After 2-4 attempts the extension fails.
( Noticed this when developing extensions )

**Comment by kgshank** [comment]
Please provide the console messages when the error occurs.

**Comment by franglais125** [comment]
Took me some time, but I was finally able to reproduce this. Here is the errors on my log:

```
JS WARNING: [/home/franglais125/.local/share/gnome-shell/extensions/disconnect-wifi@kgshank.net/extension.js 210]: reference to undefined property "_nmDevices"
Oct 14 15:04:27 v131 gnome-shell[4142]: Extension "disconnect-wifi@kgshank.net" had error: TypeError: this._network._nmDevices is undefined
```

This is on Gnome 3.26.

**Comment by kgshank** [comment]
Pushed the update to gnome extensions site. Thanks for the fixes
