### ISSUE TITLE
Gnome 41 Support?

### ISSUE THREAD

**Issue by Scotty-Trees** [kgshank/gse-disconnect-wifi#34]
Greetings,

Gnome 41 was released this month and I was wondering if/when the extension will be updated? Thank you for your time and thank you for making an amazing extension I couldn't live without! Cheers

**Comment by chrislea** [comment]
I've put in a [pull request](https://github.com/kgshank/gse-disconnect-wifi/pull/35) that adds 41 as a supported shell version.

**Comment by chrislea** [comment]
@Scotty-Trees Gnome 41 support has been added, this issue can be closed.

**Comment by Scotty-Trees** [comment]
@chrislea Thank you very much for the update and the work to keep this lovely extension up to date! Appreciate it and thanks again. See ya in 6 months ;)
