### ISSUE TITLE
Feature request: Reconnect option

### ISSUE THREAD

**Issue by anupam207** [kgshank/gse-disconnect-wifi#9]
A "reconnect" option ("disconnect" followed by "reconnect last-SSID") would be useful for users who are suffering from issues like [this](https://askubuntu.com/questions/529347/how-do-i-keep-my-wifi-from-dropping-out).

**Comment by kgshank** [comment]
The feature is already there. Test and let me know, if it doesn't work.

**Comment by anupam207** [comment]
No, I meant a single click to perform both the actions in order, not two clicks. In others DEs like unity or MATE if you click on the connected SSID, it disconnects and immediately reconnects.

**Comment by kgshank** [comment]
@anupam207,  I misunderstood the request, will enable reconnect always through preference

**Comment by anupam207** [comment]
@kgshank  Closing this, verified it works with GNOME 3.28. Any chance of having the feature on older releases, say 3.18?
